# Generated by Django 5.0.4 on 2024-04-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="creation_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="comment",
            name="published_from",
            field=models.DateField(default=None),
        ),
    ]
